# Change these first
owner: gocreating # Your GitHub username
repo: lation-status # Your GitHub repository name

# Add your sites here
sites:
  - name: Lation Official Site
    url: https://lation.app
  - name: Lation Converter
    url: https://converter.lation.app
  - name: Lation Stock
    url: https://stock.lation.app

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  cname: status.lation.app
  # Uncomment the following line if you don't have a custom domain and add your repo name
  # baseUrl: /upptime
  logoUrl: http://lation.app/logo.png
  name: Lation Status
  introTitle: "**Lation Status** is the uptime monitor and status page for lation products."
  introMessage: The status is updated every five minutes.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
